language: node_js

node_js:
  - "6"

cache:
  directories:
    - node_modules

install: 
  - npm install
  - typings install

script:
  - npm test

after_success:
  - npm run semantic-release

sudo: required